<template>
  <section class="mb-10 flex justify-center flex-wrap">
    <FeatureCard
      v-for="card in cardsData"
      :key="card.id"
      :title="card.title"
      :description="card.description"
      :icon="card.icon"
      :background-color="card.backgroundColor"
      :border-color="card.borderColor"
    ></FeatureCard>
  </section>
</template>
<script lang="ts">
import FeatureCard from "./FeatureCard.vue";

export default {
  name: "FeatureCardList",
  components: {
    FeatureCard,
  },
  setup() {
    interface CardProps {
      id: number;
      title: string;
      description: string;
      borderColor?: string;
      backgroundColor: string;
      icon: string;
    }
    const cardsData: CardProps[] = [
      {
        id: 1,
        title: "Instant Efficiency",
        description:
          "Discover the efficiency and speed of LinkSwift in managing your links. Simplify your long URLs instantly, saving time and effort with every click.",
        backgroundColor: "#222F3C",
        icon: require("../assets/efficiency.png"),
      },
      {
        id: 2,
        title: "Streamlined Access",
        description:
          "With the convenience of logging in to LinkSwift, access your saved links hassle-free. Organize and manage your content with ease, keeping everything under control from one place.",
        backgroundColor: "#2B4757",
        icon: require("../assets/access.png"),
        borderColor: "#3E879B",
      },
      {
        id: 3,
        title: "Enhanced Analytics",
        description:
          "Maximize your data analysis with LinkSwift. By tracking the activity generated by your shortened links, gain valuable insights to enhance your marketing strategies.",
        backgroundColor: "#222F3C",
        icon: require("../assets/data-analytics.png"),
      },
    ];

    return {
      cardsData,
    };
  },
};
</script>
<style></style>
