<template>
  <NavbarComponent></NavbarComponent>
  <LinkShortenerComponent></LinkShortenerComponent>
  <FeatureCardsList></FeatureCardsList>

  <!-- cards section -->
  <section class="mb-10 flex justify-center flex-wrap">
    <!-- Card one -->
    <div
      class="shadow w-56 h-64 flex flex-col rounded-2xl relative mr-0 md:mr-5 mb-5 card _ shadow-background"
    >
      <div class="flex mx-4 items-center mt-6">
        <img
          src="../assets/efficiency.png"
          alt=""
          class="bg-[#1F2531] w-9 h-9 rounded-full p-[8px] mr-2"
        />
        <h4 class="text-white text-base font-medium">Instant Efficiency</h4>
      </div>
      <p class="mx-5 text-white text-sm mt-5 leading-6">
        Discover the efficiency and speed of LinkSwift in managing your links.
        Simplify your long URLs instantly, saving time and effort with every
        click.
      </p>

      <div
        class="bg-[#3E879B] w-[100%] h-[100%] absolute -z-10 rounded-2xl opacity-10"
      ></div>
    </div>

    <!-- Card two -->
    <div
      class="shadow w-56 h-72 flex flex-col rounded-2xl relative border-2 border-[#3E879B] md:mr-5 mb-5 shadow-background"
    >
      <div class="flex mx-4 items-center mt-6">
        <img
          src="../assets/access.png"
          alt=""
          class="bg-[#1F2531] w-9 h-9 rounded-full p-[8px] mr-2"
        />
        <h4 class="text-white text-base font-medium">Streamlined Access</h4>
      </div>
      <p class="mx-5 text-white text-sm mt-5 leading-6">
        With the convenience of logging in to LinkSwift, access your saved links
        hassle-free. Organize and manage your content with ease, keeping
        everything under control from one place.
      </p>

      <div
        class="bg-[#3E879B] w-[100%] h-[100%] absolute -z-10 rounded-2xl opacity-40"
      ></div>
    </div>

    <!-- card three -->
    <div
      class="shadow w-56 h-64 flex flex-col rounded-2xl relative mb-5 shadow-background"
    >
      <div class="flex mx-4 items-center mt-6">
        <img
          src="../assets/data-analytics.png"
          alt=""
          class="bg-[#1F2531] w-9 h-9 rounded-full p-[8px] mr-2"
        />
        <h4 class="text-white text-base font-medium">Enhanced Analytics</h4>
      </div>
      <p class="mx-5 text-white text-sm mt-5 leading-6">
        Maximize your data analysis with LinkSwift. By tracking the activity
        generated by your shortened links, gain valuable insights to enhance
        your marketing strategies.
      </p>

      <div
        class="bg-[#3E879B] w-[100%] h-[100%] absolute -z-10 rounded-2xl opacity-10"
      ></div>
    </div>
  </section>

  <section class="flex mb-20 justify-center">
    <button
      class="bg-[#B2F1FF] text-[#3C3C3C] text-base font-medium h-10 w-44 rounded-lg"
    >
      Create Account
    </button>
  </section>

  <!-- <div
    v-if="showInfoCopy"
    class="absolute flex top-0 w-[100%] justify-center animate-flip-down animate-ease-in-out animate-normal"
  >
    <div
      class="flex justify-center items-center w-44 h-12 bg-[#1c2e3d] rounded-lg mt-3 shadow-info-copy"
    >
      <img src="../assets/info.png" class="w-4 h-4 mr-2" alt="" />
      <span class="text-white text-base">Copied text</span>
    </div>
  </div>

  <div
    v-else-if="showInfoCopy === false && playingAnimation === false"
    class="absolute flex top-0 w-[100%] justify-center animate-flip-down animate-once animate-ease-in-out animate-reverse animate-fill-forwards"
  >
    <div
      class="flex justify-center items-center w-44 h-12 bg-[#1c2e3d] rounded-lg mt-3 shadow-info-copy"
    >
      <img src="../assets/info.png" class="w-4 h-4 mr-2" alt="" />
      <span class="text-white text-base">Copied text</span>
    </div>
  </div> -->
</template>

<script lang="ts">
import NavbarComponent from "@/components/NavbarComponent.vue";
import LinkShortenerComponent from "@/components/LinkShortenerComponent.vue";
import FeatureCardsList from "@/components/FeatureCardsList.vue";

export default {
  name: "HomePage",

  components: { NavbarComponent, LinkShortenerComponent, FeatureCardsList },
};
</script>

<style>
.shadow-info-copy {
  box-shadow: 2px 2px 20px none;
}
.shadow-info-copy:hover {
  box-shadow: 0px 0px 80px #3e879ba8;
  transition: box-shadow 1s;
}
</style>
