<template>
  <NavbarC></NavbarC>

  <!-- input link section -->
  <section class="flex items-center flex-col mt-14">
    <h1 class="text-white text-2xl font-medium">PREMIUM URL SHORTENER</h1>
    <div
      class="bg-[#252429] w-[90%] md:w-[65%] flex h-14 mt-8 rounded-lg items-center"
    >
      <img src="../assets/link.png" alt="" class="w-5 h-5 ml-4 select-none" />
      <input
        type="text"
        class="bg-[#252429] outline-none rounded-lg text-white indent-5 ::placeholder flex-1"
        placeholder="Paste a long link"
        v-model="postData.originalLink"
      />

      <div class="w-2 h-1"></div>
      <button
        class="text-[#1b1921] bg-[#4CBED9] w-20 h-8 rounded-xl text-sm font-medium mr-5"
        @click="sendLinkToShorten"
      >
        Shorten
      </button>
    </div>
    <div
      v-show="showResponse"
      class="animate-fade-down animate-delay-50 animate-ease-in-out animate-fill-forwards flex items-center w-[90%] md:w-[65%] h-16 mt-3 shadow border-[1px] border-[#3E879B] rounded-lg rounded-br-3xl relative"
    >
      <img
        src="../assets/copy-link.png"
        alt=""
        class="w-5 h-5 ml-4 select-none mr-3 cursor-pointer"
        @click="copyLink"
      />
      <div class="flex flex-col justify-center flex-1 overflow-hidden">
        <span class="text-white text-sm font-light opacity-50"
          >Shortened link</span
        >
        <span
          class="text-[#62C5FF] text-lg font-semibold -mt-1 cursor-pointer"
          @click="redirectPage"
          id="id_linkToCopy"
          >{{ shortenedLink }}</span
        >
      </div>
      <img
        src="../assets/arrow-right.png"
        alt=""
        class="w-8 h-6 mr-5 cursor-pointer pl-2"
        @click="redirectPage"
      />
      <div
        class="bg-[#252429] opacity-[47%] w-[100%] h-[100%] absolute -z-10 rounded-br-3xl"
      >
        <!-- background div -->
      </div>
    </div>
  </section>

  <section class="my-24 flex flex-col items-center">
    <h2 class="text-center text-white text-xl font-semibold">
      Clipp.io: Streamline Your Surfing
    </h2>
    <p class="text-white text-center w-80 md:w-96 mt-7">
      Convert lengthy URLs into concise ones with a single click. Maximize
      efficiency and streamline navigation across platforms.
    </p>
  </section>

  <!-- cards section -->
  <section class="mb-10 flex justify-center flex-wrap">
    <!-- Card one -->
    <div
      class="shadow w-56 h-64 flex flex-col rounded-2xl relative mr-0 md:mr-5 mb-5 card _ shadow-background"
    >
      <div class="flex mx-4 items-center mt-6">
        <img
          src="../assets/efficiency.png"
          alt=""
          class="bg-[#1F2531] w-9 h-9 rounded-full p-[8px] mr-2"
        />
        <h4 class="text-white text-base font-medium">Instant Efficiency</h4>
      </div>
      <p class="mx-5 text-white text-sm mt-5 leading-6">
        Discover the efficiency and speed of LinkSwift in managing your links.
        Simplify your long URLs instantly, saving time and effort with every
        click.
      </p>

      <div
        class="bg-[#3E879B] w-[100%] h-[100%] absolute -z-10 rounded-2xl opacity-10"
      ></div>
    </div>

    <!-- Card two -->
    <div
      class="shadow w-56 h-72 flex flex-col rounded-2xl relative border-2 border-[#3E879B] md:mr-5 mb-5 shadow-background"
    >
      <div class="flex mx-4 items-center mt-6">
        <img
          src="../assets/access.png"
          alt=""
          class="bg-[#1F2531] w-9 h-9 rounded-full p-[8px] mr-2"
        />
        <h4 class="text-white text-base font-medium">Streamlined Access</h4>
      </div>
      <p class="mx-5 text-white text-sm mt-5 leading-6">
        With the convenience of logging in to LinkSwift, access your saved links
        hassle-free. Organize and manage your content with ease, keeping
        everything under control from one place.
      </p>

      <div
        class="bg-[#3E879B] w-[100%] h-[100%] absolute -z-10 rounded-2xl opacity-40"
      ></div>
    </div>

    <!-- card three -->
    <div
      class="shadow w-56 h-64 flex flex-col rounded-2xl relative mb-5 shadow-background"
    >
      <div class="flex mx-4 items-center mt-6">
        <img
          src="../assets/data-analytics.png"
          alt=""
          class="bg-[#1F2531] w-9 h-9 rounded-full p-[8px] mr-2"
        />
        <h4 class="text-white text-base font-medium">Enhanced Analytics</h4>
      </div>
      <p class="mx-5 text-white text-sm mt-5 leading-6">
        Maximize your data analysis with LinkSwift. By tracking the activity
        generated by your shortened links, gain valuable insights to enhance
        your marketing strategies.
      </p>

      <div
        class="bg-[#3E879B] w-[100%] h-[100%] absolute -z-10 rounded-2xl opacity-10"
      ></div>
    </div>
  </section>

  <section class="flex mb-20 justify-center">
    <button
      class="bg-[#B2F1FF] text-[#3C3C3C] text-base font-medium h-10 w-44 rounded-lg"
    >
      Create Account
    </button>
  </section>

  <div
    v-if="showInfoCopy"
    class="absolute flex top-0 w-[100%] justify-center animate-flip-down animate-ease-in-out animate-normal"
  >
    <div
      class="flex justify-center items-center w-44 h-12 bg-[#1c2e3d] rounded-lg mt-3 shadow-info-copy"
    >
      <img src="../assets/info.png" class="w-4 h-4 mr-2" alt="" />
      <span class="text-white text-base">Copied text</span>
    </div>
  </div>

  <div
    v-else-if="showInfoCopy === false && playingAnimation === false"
    class="absolute flex top-0 w-[100%] justify-center animate-flip-down animate-once animate-ease-in-out animate-reverse animate-fill-forwards"
  >
    <div
      class="flex justify-center items-center w-44 h-12 bg-[#1c2e3d] rounded-lg mt-3 shadow-info-copy"
    >
      <img src="../assets/info.png" class="w-4 h-4 mr-2" alt="" />
      <span class="text-white text-base">Copied text</span>
    </div>
  </div>
</template>

<script lang="ts">
import NavbarC from "@/components/NavbarC.vue";
import { ref } from "vue";

export default {
  name: "HomePage",
  setup() {
    const postData = ref({
      originalLink: "",
    });

    const showResponse = ref(false);
    const shortenedLink = ref("");

    const showInfoCopy = ref(false);
    const playingAnimation = ref(true);

    const sendLinkToShorten = async () => {
      const requestOptions = {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(postData.value),
      };

      fetch("http://localhost:5000/api/link/createLinkShorter", requestOptions)
        .then((response) => {
          if (!response.ok) {
            throw new Error("Error");
          }

          return response.json();
        })
        .then((data) => {
          showResponse.value = true;
          shortenedLink.value = data.data.shorterLink;
          console.log(data);
        })
        .catch((error) => {
          console.log("ERROR!!", error);
        });
    };

    const redirectPage = () => {
      window.open(shortenedLink.value, "_blank");
    };

    const copyLink = () => {
      const link = document.getElementById("id_linkToCopy")?.innerText;
      if (link) {
        navigator.clipboard.writeText(link);
        showInfoCopyAnimation();
      }
    };

    const showInfoCopyAnimation = () => {
      showInfoCopy.value = true;

      setTimeout(() => {
        showInfoCopy.value = false;
        playingAnimation.value = false;
        setTimeout(() => {
          playingAnimation.value = true;
        }, 1000);
      }, 5000);
    };

    return {
      sendLinkToShorten,
      postData,
      showResponse,
      shortenedLink,
      redirectPage,
      copyLink,
      showInfoCopy,
      playingAnimation,
    };
  },
  components: { NavbarC },
};
</script>

<style>
.shadow-info-copy {
  box-shadow: 2px 2px 20px none;
}
.shadow-info-copy:hover {
  box-shadow: 0px 0px 80px #3e879ba8;
  transition: box-shadow 1s;
}
</style>
